### ISSUE TITLE
Make route styles a stacked bar graph

### ISSUE THREAD

**Issue by jdillard** [jdillard/personal-site#32]
Horizontal stacked bar charts V4 examples:
* https://bl.ocks.org/Andrew-Reid/0aedd5f3fb8b099e3e10690bd38bd458
* https://bl.ocks.org/caravinden/32a3d192e0e5f6af81f4bcc12adda8f7

**TODOS**:
- [x] remove hardcoded `sport` keys from `logdata.ticks` object
- [x] add a style break out  to `logdata.ticks` to show the count of different styles
- [x] grab the different styles from `logdata.ticks` to populate the legend
- [x] make the style colors consistent
- [x] fix legend overlap by making it horizontal and underneath
- [x] pick better colors
