### ISSUE TITLE
Add table of selected routes below Route Pyramid

### ISSUE THREAD

**Issue by jdillard** [jdillard/personal-site#39]
Display:

- [x] Date
- [x] Name
- [x] Type
- [x] Style
- [x] Rating

**TODO**:

- [ ] Sort by date, etc
- [x] Make mobile friendly
- [x] add to default data set (Joe Dirtbag's)
- [ ] Add total count

**Comment by jdillard** [comment]
Closing as the table is stable enough.
